(FM-2783) Fix Module Failure on WMF5 base resources
If a user tries to run the module on a Windows system running WMF 5
errors will occur when applying manifests with DSC resources specified:

~~~
Error: /Stage[main]/Main/Dsc_file[tmp_folder]: Could not
evaluate: WARNING: The configuration 'PuppetConfiguration' is loading
one or more
built-in resources without explicitly importing associated modules. Add
Import-DscResource -ModuleName 'PSDesiredStateConfiguration' to your
configuration to avoid this message.
False
~~~

Without this fix the warning will continue to occur producing nothing
to move forward with in setting the configuratin.

This is due to importing both name and modulename, where we should only
be importing by modulename.